### ISSUE TITLE
Migration out of Amsterdam server (164.92.153.78)

### ISSUE THREAD

**Issue by kaveh3000** [aviertech/goodfellas-vpn#1]
با راه‌اندازی سرور جدید در ورشو که کارآیی لازم را دارد، سرور قبلی در آمستردام با IP برای تخلیه کاربران و انتقال آنها به سرور جدید در نظر گرفته شده است.

 تنها تغییر لازم برای این کار توسط کاربران  در نرم‌افزار‌های وی پی ان، عوض کردن فیلد نام سرور از 164.92.153.78به v2r.aviertechnologies.com می‌باشد.
 
سرویس وی پی ان روی سرور آمستردام در تاریخ ۱۰ دی برچیده خواهد شد.

**Comment by alishams46** [comment]
جابجایی به ورشو چه امکاناتی اضافه میکنه؟ کم کردن فاصله فیزیکی با ایران؟

**Comment by kaveh3000** [comment]
> جابجایی به ورشو چه امکاناتی اضافه میکنه؟ کم کردن فاصله فیزیکی با ایران؟

این هدف بود، به علاوه، افزایش انعطاف پذیری همانطور که در برخی از پیام های صوتی خود توضیح دادم.
ایده این است که سرورها را یک بار (هر سه یا چهار هفته) بچرخانید. بنابراین، ما خیلی به یک سرور یا IP وابسته نیستیم. این به ما تحمل خطای بیشتری می دهد.
